---
- name: Write LDAP sync config file
  copy:
    content: "{{ config | to_nice_yaml }}"
    dest: /etc/origin/master/ldapsync-config.yml

- name: Write LDAP sync whitelist file
  copy:
    content: "{{ whitelist | default([]) | join('\n') }}"
    dest: /etc/origin/master/ldapsync-whitelist.txt

- name: Write LDAP sync blacklist file
  copy:
    content: "{{ blacklist | default([]) | join('\n') }}"
    dest: /etc/origin/master/ldapsync-blacklist.txt

- name: Sync LDAP groups
  command: "oc adm groups sync --whitelist=/etc/origin/master/ldapsync-whitelist.txt --blacklist=/etc/origin/master/ldapsync-blacklist.txt  --sync-config=/etc/origin/master/ldapsync-config.yml --confirm"

- name: Prune LDAP groups
  command: "oc adm groups prune --whitelist=/etc/origin/master/ldapsync-whitelist.txt --blacklist=/etc/origin/master/ldapsync-blacklist.txt  --sync-config=/etc/origin/master/ldapsync-config.yml --confirm"

- name: Configure LDAP sync cron job
  cron:
    name: "Synchronize OpenShift groups with LDAP"
    user: root
    cron_file: openshift_ldapsync
    special_time: hourly
    job: "oc adm groups sync --whitelist=/etc/origin/master/ldapsync-whitelist.txt --blacklist=/etc/origin/master/ldapsync-blacklist.txt  --sync-config=/etc/origin/master/ldapsync-config.yml --confirm >/dev/null"

- name: Configure LDAP prune cron job
  cron:
    name: "Prune OpenShift groups with LDAP"
    user: root
    cron_file: openshift_ldapsync
    special_time: hourly
    job: "oc adm groups prune --whitelist=/etc/origin/master/ldapsync-whitelist.txt --blacklist=/etc/origin/master/ldapsync-blacklist.txt  --sync-config=/etc/origin/master/ldapsync-config.yml --confirm >/dev/null"

- name: Assign roles to synched groups
  openshift_policy:
    cluster_roles: "{{ item.cluster_roles }}"
    groups: "{{ item.groups }}"
  with_items: "{{ policy | default([]) }}"
